export default function index() {
  return (
    <>
      {/* ==================================  Header One ================================== */}
      <div>
        <div className="flex items-center">
          <img
            src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fbadge%201.1bff520f.png&w=32&q=75"
            alt=""
          />
          <h1 className="text-[20px] text-[#000000] font-normal ml-1">
            KEYWORD RANKINGS
          </h1>
        </div>
        <p className="text-[#434343] text-[14px] font-normal mt-2">
          A summary of how your tracked keywords are ranking in Google.
        </p>
      </div>

      {/* ==================================  Header Two ================================== */}

      <div>
        <div className="flex items-center">
          <img
            src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flove%201.2c7d84cd.png&w=32&q=75"
            alt=""
          />
          <h1 className="text-[20px] text-[#000000] font-normal ml-1">
            KEYWORD DATA
          </h1>
        </div>
        <p className="text-[#434343] text-[14px] font-normal mt-2">
          A summary of how your tracked keywords are performing along with
          30-day Data.
        </p>
      </div>

      {/* ==================================  Header Three ================================== */}

      <div>
        <div className="flex items-center max-w-full justify-between">
          <div className="flex items-center">
            <img
              src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsearch%201.02229d35.png&w=32&q=75"
              alt=""
            />
            <h1 className="text-[20px] text-[#000000] font-normal ml-1">
              WEB AUDIT
            </h1>
          </div>
          <div className="btn">
            <button className="bg-[#0047FF] rounded-[7px] text-white mx-1 py-1 px-3 font-medium">
              View Full
            </button>
            <button className="bg-[#0047FF] rounded-[7px] text-white mx-1 py-1 px-3 font-medium">
              View Full Audit
            </button>
          </div>
        </div>
        <p className="text-[#434343] text-[14px] font-normal mt-2">
          our overall SEO score based on an analysis of all pages on your site.
        </p>
      </div>

            {/* ==================================  Header Four ================================== */}
    <div>
        <div className="flex items-center">
          <img
            src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fbacklinks%201.f1273105.png&w=32&q=75"
            alt=""
          />
          <h1 className="text-[20px] text-[#000000] font-normal ml-1">
          BACKLINKS
          </h1>
        </div>
        <p className="text-[#434343] text-[14px] font-normal mt-2">
        The number of incoming links to your site from other sites on the Web.
        </p>
      </div>



        {/* ==================================  Header Five ================================== */}
    <div>
        <div className="flex items-center">
        <img
            src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fbadge%201.1bff520f.png&w=32&q=75"
            alt=""
          />
          <h1 className="text-[20px] text-[#000000] font-normal ml-1">
          NEW RANKED KEYWORDS
          </h1>
        </div>
        <p className="text-[#434343] text-[14px] font-normal mt-2">
        These are keywords that have showed up in rankings atleast once in the within 7-10 days of the last update, these are potential keywords that have no stable rankings but may prove to be beneficial if focused on.
        </p>
      </div>


       {/* ==================================  Header Six ================================== */}
    <div>
        <div className="flex items-center">
        <img
            src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fbadge%201.1bff520f.png&w=32&q=75"
            alt=""
          />
          <h1 className="text-[20px] text-[#000000] font-normal ml-1">
          KEYWORD SUGGESTIONS
          </h1>
        </div>
        <p className="text-[#434343] text-[14px] font-normal mt-2">
        These keywords are generated by using your currently tracked keywords as a base and for further extension of intent and depth of niche, you can add these to your list as well as add some more content around these keywords for depth.
        </p>
      </div>

    </>
  );
}
